accessing
harassementReactionPicturesUrls
	^ #('http://p9.storage.canalblog.com/97/90/943891/110975754.gif'
	'http://m.memegen.com/30idna.jpg' 
	'https://media.giphy.com/media/XknChYwfPnp04/giphy.gif'
	'https://media.giphy.com/media/FCeqsn7FF2xIQ/giphy.gif' 	'https://www.reactiongifs.us/wp-content/uploads/2018/02/giphy-downsized-1.gif' 	'https://78.media.tumblr.com/tumblr_m13lj35AKg1r98lguo2_500.gif'
	'https://media.giphy.com/media/3owzVZ1XWDzHoWN7zi/giphy.gif' 	'https://img.buzzfeed.com/buzzfeed-static/static/2014-05/enhanced/webdr06/12/13/anigif_enhanced-15975-1399915890-17.gif' 	'http://gif-finder.com/wp-content/uploads/2016/01/Emilia-Clarke-Eye-Roll.gif')